- name: Massages
  hosts: all
  become: yes

  vars:
    var1: 1
    var2: 2
    var3: 3

  tasks:
    - name: Print vars
      debug: 
        var: var1
    
    - debug:
        msg: "number {{var2}}"