- name: Install apache
  hosts: hosts
  become: yes

  vars:
    packages:
              - httpd
              - tree
              - rsync
  tasks:
  - name: Install apache
    dnf:
      pkg: "{{ packages }}"
      state: latest